config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'
  devise_for :users
  get 'home' => 'pages/home', as: :home
  resources :users do
    resources :likes
    resources :reports
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
      resources :comments, only: [:create]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :reply, class_name: 'Comment', optional: true

  has_many :replies, class_name: 'Comment', foreign_key: 'comment_id'
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy

  validates :body, presence: true

  scope :with_no_replies, -> { where(comment_id: nil) }
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  scope :recent, -> { order(created_at: :desc) }
  scope :published, -> { where(published: true) }
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :reportable, polymorphic: true
  belongs_to :user

  validates :body, presence: true

  scope :recent, -> { order(created_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :lockable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :reports, dependent: :destroy

  enum role: { Member: 'Member', Moderator: 'Moderator', Admin: 'Admin' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      @comment.errors.full_messages.join('\n')
      redirect_back(fallback_location: @post)
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id, :comment_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    like = current_user.likes.new
    like.likeable_type = params[:model]
    like.likeable_id = params[:id]
    if like.save!
      redirect_back(fallback_location: root_path)
    else
      like.errors.full_messages.join('\n')
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    like = Like.find_by(user_id: params[:user_id], likeable_id: params[:id])
    if like.destroy
      redirect_back(fallback_location: root_path)
    else
      like.errors.full_messages.join('\n')
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    @first_post = Post.find(Post.published.joins(:likes).group(:likeable_id).count.max_by{|k,v| v}.first)
    @posts = Post.published.recent.all
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, except: %i[index new create]
  after_action :verify_authorized

  def index
    authorize Post
    @posts = policy(Post).index?
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:replies, :likes, :user).order(created_at: :desc).with_no_replies
    if @post.likes.any?
      @liked_post = true
    end
    if @post.reports.any?
      @reported_post = true
    end
    @report = current_user.reports.new
  end

  def new
    @post = current_user.posts.new
    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)
    authorize @post
    if @post.save
      flash[:notice] = 'Added successfully'
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Updated successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash[:alert] = @post.errors.full_messages.join('\n')
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Deleted successfully'
      return redirect_to user_posts_path(current_user)
    else
      flash[:alert] = @post.errors.full_messages.join('\n')
    end
    redirect_to user_post_path(current_user, @post)
  end

  def publish
    @post.update(published: true)
    redirect_to user_posts_path(current_user)
  end

  def unpublish
    @post.update(published: false)
    redirect_to user_posts_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :authenticate_user!

  def create
    @report = current_user.reports.new
    @report.reportable_type = params[:model]
    @report.reportable_id = params[:id]
    @report.body = params[:report][:body]
    if @report.save
      flash[:notice] = 'Reported successfully'
      redirect_back(fallback_location: root_path)
    else
      @report.errors.full_messages.join('\n')
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @post = Post.includes(:user).find(params[:id])
    @reports = @post.reports
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: %i[index]
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Edited successfully'
      redirect_to @user
    else
      flash[:alert] = 'Unable to edit'
      render 'edit'
    end
  end

  def destroy
    return redirect_to users_path, alert: 'You cannot delete yourself!' if current_user == @user
    if @user.destroy
      flash[:notice] = 'Deleted successfully'
      redirect_to users_path
      return
    else
      flash[:alert] = 'Unable to delete'
    end
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:email, :role)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def likedByUser(comment)
    comment.likes.where(user_id: current_user.id).exists?
  end
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/posts/_comment_form.html.erb
<div class=" offset-lg-1">
  <h5><span><i class="far fa-comment-dots fa-lg"></i> Comments</span></h5>
</div>
<div class="row ">
  <div class="col-md-12 offset-md-1 col-lg-4 offset-lg-4"  >
    <%= form_with(model: [ @post, @comment ], url: user_post_comments_path(current_user, @post), local: true, html: { class: "form-group" }) do |form| %>
      <%= form.text_field :body, class:"form-control ", placeholder:"Write awesome comments here." %>
      <br>
      <%= form.submit 'Comment', class: "btn btn-success mx-auto d-block" %>
    <% end %>
  </div>
</div>

app/views/posts/_comments.html.erb
<div class="row">
  <% if @comments.any? %>
    <div class="col-lg-10 offset-md-1 comment-container">
      <% @comments.each do |comment| %>
        <ul class="list-group">
          <li class="list-group-item align-items-center">
          <div class="container">
            <div class="row d-flex justify-content-between">
              <div class="col-lg-auto">
                <span class="badge">
                  <%= comment.created_at.strftime("%e/%b/%y[%I :%M %p]") %>
                  By:  <%= link_to "#{comment.user.email}",user_path(comment.user) %>
                </span>
              </div>
              <div class="col-lg-4">
                <%= comment.body %>
              </div>
              <div class='row'>
                  <div class="col-lg-auto">
                  <a class="badge badge-pill badge-primary" data-toggle="collapse" href="#collapse<%= comment.id %>" aria-expanded="false" aria-controls="collapse<%=comment.id %>">
                      <span><i class="fas fa-reply"></i> Reply</span>
                  </a>
                </div>
                <div class="col-lg-auto">
                  <% if likedByUser(comment) %>
                    <%= link_to(user_like_path(id: comment.id), method: :delete, remote: true, class: 'badge badge-pill badge-secondary') do %>
                      <span><i class="fas fa-thumbs-down"></i> Unlike</span>
                    <% end %>
                  <% else %>
                    <%= link_to(user_likes_path(current_user, model: 'Comment', id: comment.id), method: :post, remote: true, class: 'badge badge-pill badge-primary') do %>              
                      <span><i class="fas fa-thumbs-up"></i> Like</span>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="collapse col-lg-6 offset-lg-3" id="collapse<%=comment.id %>">
                  <%= form_with(model: [ @post, @comment ], url: user_post_comments_path(current_user, @post), local: true, html: { class: "form-group" }) do |form| %>
                    <%= form.text_field :body, class:"form-control ", placeholder:"Write an amazing reply..." %>
                    <%= form.hidden_field :comment_id, value: comment.id %>
                    <br>
                    <%= form.submit 'Reply', class: "badge badge-success mx-auto d-block" %>
                  <% end %>
              </div>
            </div>
            <% if comment.replies.any? %>
              <div class='container'>
                <div class="row">
                  <h5>Replies:</h5>
                  <ul class="list-group col-lg-9 offset-lg-3 ">
                  <% comment.replies.each do |reply| %>
                    <li class="list-group-item border border-primary"><%= link_to "#{comment.user.email}: ",user_path(reply.user), class: 'badge' %> <%= reply.body %></li>
                  <% end %>
                  </ul>
                </div>
              </div>
              <% end %>
          </div>
        </li>
      </ul> 
      <% end %>
    </div>
  <% else %>
    <div class="container p-50">
        <h4 class="text-center text-secondary ">No comments yet...</h4>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: [ :user, @post ], local: true, html: { class: "form-group" }) do |form| %>
  <% if @post.errors.any? %>
    <div class="lead">
      <h5><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h5>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <div class="alert alert-danger lead" role="alert">
            <li><%= message %></li>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :title, class:"form-control ", placeholder:"Enter Title"  %>
  <%= form.text_area :body, class:"form-control", id: "editor" %>
  <br>
  <%= form.submit 'Submit', class: "btn btn-primary mx-auto d-block" %>
<% end %>

app/views/posts/_report_modal.html.erb
<!-- Modal trigger button -->
      <% if @reported_post %>
        <button type="button" class="btn btn-danger rounded-pill">
          <span><i class="disabled fas fa-exclamation-triangle"></i> Reported</span>
        </button>
      <% else %>
        <button type="button" class="btn btn-danger rounded-pill" data-toggle="modal" data-target="#reportModalCenter">
          <span><i class="fas fa-exclamation-triangle"></i> Report</span>
        </button>
      <% end %>
      <!-- Modal -->
      <div class="modal fade" id="reportModalCenter" tabindex="-1" role="dialog" aria-labelledby="reportModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="reportModalLongTitle">Reporting <strong><%= @post.title %></strong></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= form_with(model: [ :user, @report ], local: true, html: { class: "form-group" }) do |form| %>
                <% if @report.errors.any? %>
                  <div class="lead">
                    <h5><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h5>
                    <ul>
                      <% @report.errors.full_messages.each do |message| %>
                        <div class="alert alert-danger lead" role="alert">
                          <li><%= message %></li>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <%= form.label 'This post is :' %>
                <%= form.select :body, [ 'Spam','Inappropriate','Copied', 'Racial content' ], {} , required: true, class: 'custom-select w-50 mb-3' %>
                <%= hidden_field_tag "model", 'Post' %>
                <%= hidden_field_tag "id", @post.id %>
                <%= form.submit 'Report', class: "btn btn-danger rounded-pill mx-auto d-block" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

app/views/posts/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container ">
    <h2 class="display-4 text-center">Editing <%= @post.title %></h2>
    <div class="lead d-flex justify-content-center ">
        <div class="w-50;">
            <%= render 'form', locals: { post: @post } %>
        </div>
    </div>
  </div>

app/views/posts/index.html.erb
<h2 class="text-center">List of Posts</h2>
<div class="container">
  <div class="row justify-content-end">
    <%= link_to(new_user_post_path, class: "btn btn-primary") do %>
      <i class="far fa-edit"></i>
    <% end %>
  </div>
</div>
<% if @posts.any? %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <% if current_user.Admin? || current_user.Moderator? %>
        <th scope="col">Status</th>
        <th scope="col">Reports</th>
      <% end %>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <% @posts.each do |post| %>
                <td><%= post.id%></td>
                <td><%= post.title%></td>
                <% if current_user.Admin? || current_user.Moderator? %>
                  <% if post.published %>
                    <td class="text-success">Published</td>
                  <% else %>
                    <td class="text-danger">Unpublished</td>
                  <% end %>
                  <td><%= post.reports.length%></td>
                <% end %>                
                <td>
                  <%= link_to(user_post_path(post.user, post), class: 'btn btn-sm btn-info') do %>
                    <i class="fas fa-eye"></i>
                  <% end %> 
                  <% if (post.user == current_user)  || current_user.Admin? || current_user.Moderator? %>
                    | <%= link_to(edit_user_post_path(post.user, post), class: 'btn btn-sm btn-secondary') do %>
                          <i class="fas fa-pencil-alt"></i>
                      <% end %> 
                  | <%= link_to(user_post_path(post.user, post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger') do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %> 
                  <% end %>
                  <% if current_user.Admin? || current_user.Moderator? %>
                    | <% if post.published %>
                        <%= link_to "Unpublish", unpublish_user_post_path(post.user, post), method: :put, class: 'btn btn-sm btn-danger' %>
                      <% else %>
                        <%= link_to "Publish", publish_user_post_path(post.user, post), method: :put, class: 'btn btn-sm btn-success' %>                  
                      <% end %>
                  <% end %>
                </td>
            
        </tr>
          </tbody>
            <% end %>
</table>
<% else %>
    <div class="container p-50">
        <h4 class="text-center text-secondary ">No data to show ...</h4>
    </div>
<% end %>

app/views/posts/new.html.erb
<div class="jumbotron jumbotron-fluid">
    <div class="container ">
        <h2 class="display-4 text-center">Adding new post</h2>
        <div class="lead d-flex justify-content-center ">
            <div class="w-50">
                <%= render 'form', locals: { post: @post } %>
            </div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12 offset-md-1 col-lg-9 offset-lg-2 post-container">
    <ul class="list-group">
      <li class="list-group-item align-items-center">
        <h1 class="text-center"><%= @post.title %></h1>
        <p class="text-center"><%= distance_of_time_in_words(@post.created_at, Time.now)+ ' ago' %></p>
        <div class="text-center">
          <%= sanitize @post.body %>
      </li>
    </ul>
  </div>
</div>

<div class="row justify-content-end">
  <div class="col-md-auto ">
    <% if current_user.Admin? || current_user.Moderator? %>
      <%= link_to(user_reports_path(id: @post.id), class: 'btn btn-danger rounded-pill') do %>              
          <span><i class="far fa-list-alt"></i> View Reports</span>
      <% end %>
    <% end %>
    <% if @liked_post %>
      <%= link_to(user_like_path(id: @post.id), method: :delete, remote: true, class: 'btn btn-secondary rounded-pill') do %>              
        <span><i class="fas fa-thumbs-down"></i> Unlike</span>
      <% end %>
    <% else %>
      <%= link_to(user_likes_path(current_user, model: 'Post', id: @post.id), method: :post, remote: true, class: 'btn btn-primary rounded-pill') do %>              
        <span><i class="fas fa-thumbs-up"></i> Like</span>
      <% end %>
    <% end %>
    <%= render 'report_modal', locals: { reported_post: @reported_post, report: @report }%>
  </div>
</div>

<hr/>

<%= render 'comment_form', locals: { post: @post, comment: @comment}%>

<hr/>
<%= render 'comments', locals: { comments: @comments } %>

app/views/reports/index.html.erb
<h2 class="text-center">List of Reports</h2>
<% if @reports.any? %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Report Id</th>
      <th scope="col">Post</th>
      <th scope="col">Reported for</th>
      <th scope="col">Reported by</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <% @reports.each do |report| %>
                <td><%= report.id%></td>
                <td><%= link_to @post.title, user_post_path(@post.user, @post.id) %></td>
                <td><%= report.body %></td>
                <td><%= report.user.email%></td>
                <td>
                  <%= link_to(user_post_path(@post.user, @post.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger') do %>
                      <i class="far fa-trash-alt"></i>
                  <% end %> | 
                      <%= link_to "Unpublish", unpublish_user_post_path(@post.user, @post.id), method: :put, class: 'btn btn-sm btn-danger' %>
                </td>
        </tr>
          </tbody>
            <% end %>
</table>
<% else %>
    <div class="container p-30">
        <h4 class="text-center text-secondary ">No reports to show ...</h4>
    </div>
<% end %>

app/views/users/_form.html.erb
  <%= form_with(model: @user, local: true, html: { class: "container form-group" }) do |form| %>
    <% if @user.errors.any? %>
      <div class="lead">
        <h5><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h5>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <div class="alert alert-danger lead" role="alert">
              <li><%= message %></li>
            </div>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.label :email,"Email"  %>
    <%= form.text_field :email, class:"form-control ", placeholder:"Enter email" %>
    <%= form.label :role,"Role" %>
    <%= form.select :role, [ 'Member','Moderator','Admin'], {} , required: true, class: 'custom-select' %>
    <br>
    <%= form.submit 'Submit', class: "btn btn-primary mx-auto d-block" %>
  <% end %>

app/views/users/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container ">
    <h2 class="display-4 text-center">Editing <%= @user.email%></h2>
    <div class="lead d-flex justify-content-center ">
        <div class="w-50">
            <%= render 'form', locals: {user: @user}%>
        </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2 class="text-center">List of Users</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <%# <th scope="col">Name</th> %>
      <th scope="col">Email</th>
      <th scope="col">Type</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @users.each do |user| %>
      <td><%= user.id%></td>
      <td><%= user.email %></td>
      <td><%= user.role%></td>
      <td>
        <%= link_to(user_path(user), class: 'btn btn-sm btn-info') do %>
          <i class="fas fa-eye"></i>
        <% end %> | 
        <% if current_user.Admin? %>
          <%= link_to(edit_user_path(user), class: 'btn btn-sm btn-secondary') do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %> | 
          <%= link_to(user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger') do %>
            <i class="fas fa-trash-alt"></i>
          <% end %> 
        <% end %> 
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container ">
    <h2 class="display-4 text-center">Adding new user</h2>
    <div class="lead d-flex justify-content-center ">
        <div class='container'>
            <%= render 'form', locals: { user: @user } %>
        </div>
    </div>
  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container ">
    <h1 class="display-5 text-center"><%= @user.email %></h1>
    <div class="lead text-center">
      <div class="mx-auto d-block w-50 text-center">      
        <form>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-3 col-form-label font-weight-bold" >Email:</label>
            <div class="col-sm-8">
              <input type="text" readonly class="form-control-plaintext text-center" id="staticEmail" value="<%= @user.email %>">
            </div>
          </div>
          <div class="form-group row">
            <label for="staticRole" class="col-sm-3 col-form-label font-weight-bold" >Role Type:</label>
            <div class="col-sm-8">
              <input type="text" readonly class="form-control-plaintext text-center" id="staticRole" value="<%= @user.role %>">
            </div>
          </div>
          <div class="form-group row">
            <label for="staticJoinDate" class="col-sm-3 col-form-label font-weight-bold" >Joined:</label>
            <div class="col-sm-8">
              <input type="text" readonly class="form-control-plaintext text-center" id="staticJoinedDate" value="<%= distance_of_time_in_words(@user.created_at, Time.now)+ ' ago' %>">
            </div>
          </div>
          <div class="form-group row">
            <label for="staticUpdateDate" class="col-sm-3 col-form-label font-weight-bold" >Updated:</label>
            <div class="col-sm-8">
              <input type="text" readonly class="form-control-plaintext text-center" id="staticUpdateDate" value="<%= @user.updated_at.localtime %>">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>